dist: trusty
sudo: required
before_install:
language: python
python:
 - '3.6'
install:
 - pip install -r requirements.txt
 - python setup.py install
 - pip install coveralls
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
script:
 - coverage run --source=talos ./test_script.py
after_success: coveralls
